export const susHabit = [
  { ID: 1, Habit: "Walk to Work", Score: 4 },
  { ID: 2, Habit: "Plant Based Meal", Score: 7 },
  { ID: 3, Habit: "Vegetarian", Score: 9 },
  { ID: 4, Habit: "Cycle to work", Score: 8 },
  { ID: 5, Habit: "Recycling", Score: 4 },
  { ID: 6, Habit: "Compost Bin", Score: 4 },
  { ID: 7, Habit: "Turn off tap when burshing teeth", Score: 2 },
  { ID: 8, Habit: "Turn off tap when shaving", Score: 2 },
  { ID: 9, Habit: "Return bottles or cans", Score: 3 },
  { ID: 10, Habit: "Turn off tap when burshing teeth", Score: 2 },
  { ID: 11, Habit: "Turn off tap when shaving", Score: 2 },
  { ID: 12, Habit: "Return bottles or cans", Score: 3 },
  { ID: 13, Habit: "Turn off tap when burshing teeth", Score: 2 },
  { ID: 14, Habit: "Turn off tap when shaving", Score: 2 },
  { ID: 15, Habit: "Return bottles or cans", Score: 3 },
  { ID: 16, Habit: "Turn off tap when burshing teeth", Score: 2 },
  { ID: 17, Habit: "Turn off tap when shaving", Score: 2 },
  { ID: 18, Habit: "Return bottles or cans", Score: 3 },
];
